---
name: "Setup for MISP"
description: "Setup or common steps in testing misp on github"

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4.3.1
      with:
        version: v3.14.4
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        check-latest: true
